package th.ac.ku.kps.eng.cpe.datasecurity.model;
// Generated Oct 26, 2023, 1:21:36 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

	private Integer feedbackId;
	@JsonIgnore
	private User user;
	private Date date;
	private String text;

	public Feedback() {
	}

	public Feedback(User user, Date date, String text) {
		this.user = user;
		this.date = date;
		this.text = text;
	}

	public Integer getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(Integer feedbackId) {
		this.feedbackId = feedbackId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
