package th.ac.ku.kps.eng.cpe.datasecurity.model;
// Generated Oct 27, 2023, 9:37:47 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Refreshtoken generated by hbm2java
 */
public class Refreshtoken implements java.io.Serializable {

	private Integer refreshtokenId;
	@JsonIgnore
	private User user;
	private String token;
	private Date expiryDate;

	public Refreshtoken() {
	}

	public Refreshtoken(User user, String token, Date expiryDate) {
		this.user = user;
		this.token = token;
		this.expiryDate = expiryDate;
	}

	public Integer getRefreshtokenId() {
		return this.refreshtokenId;
	}

	public void setRefreshtokenId(Integer refreshtokenId) {
		this.refreshtokenId = refreshtokenId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

}
