package th.ac.ku.kps.eng.cpe.datasecurity.model;
// Generated Oct 16, 2023, 11:42:57 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Scoreboard generated by hbm2java
 */
public class Scoreboard implements java.io.Serializable {

	private Integer scoreId;
	@JsonIgnore
	private User user;
	private String level;
	private int score;
	private Integer time;

	public Scoreboard() {
	}

	public Scoreboard(User user, String level, int score) {
		this.user = user;
		this.level = level;
		this.score = score;
	}

	public Scoreboard(User user, String level, int score, Integer time) {
		this.user = user;
		this.level = level;
		this.score = score;
		this.time = time;
	}

	public Integer getScoreId() {
		return this.scoreId;
	}

	public void setScoreId(Integer scoreId) {
		this.scoreId = scoreId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

}
