package th.ac.ku.kps.eng.cpe.datasecurity.model;
// Generated Oct 16, 2023, 11:42:57 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private Integer typeId;
	private String typeName;
	@JsonIgnore
	private List<Cipher> ciphers = new ArrayList<Cipher>();

	public Type() {
	}

	public Type(String typeName) {
		this.typeName = typeName;
	}

	public Type(String typeName, List<Cipher> ciphers) {
		super();
		this.typeName = typeName;
		this.ciphers = ciphers;
	}

	public Integer getTypeId() {
		return typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public List<Cipher> getCiphers() {
		return ciphers;
	}

	public void setCiphers(List<Cipher> ciphers) {
		this.ciphers = ciphers;
	}

	

}
