package th.ac.ku.kps.eng.cpe.datasecurity.model;
// Generated Oct 16, 2023, 11:42:57 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String email;
	private String username;
	private String phoneNumber;
	@JsonIgnore
	private List<Role> roles = new ArrayList<Role>();
	@JsonIgnore
	private List<Scoreboard> scoreboards = new ArrayList<Scoreboard>();

	public User() {
	}

	public User(String email, String username, String phoneNumber) {
		this.email = email;
		this.username = username;
		this.phoneNumber = phoneNumber;
	}

	public User(String email, String username, String phoneNumber, List<Role> roles, List<Scoreboard> scoreboards) {
		super();
		this.email = email;
		this.username = username;
		this.phoneNumber = phoneNumber;
		this.roles = roles;
		this.scoreboards = scoreboards;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public List<Scoreboard> getScoreboards() {
		return scoreboards;
	}

	public void setScoreboards(List<Scoreboard> scoreboards) {
		this.scoreboards = scoreboards;
	}


}
